services:
  - type: web
    name: portfolio-miftah
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://portfolio-miftah.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: portfolio-miftah-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local

databases:
  - name: portfolio-miftah-db
    plan: free
    databaseName: portfolio
    user: portfolio
